version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: cantina_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "peterTest123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cantina_api
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  sql_data:
